# This workflow will run Crowdin Action that will upload new texts to Crowdin, download the newest translations and create a PR
# For more information see: https://github.com/crowdin/github-action

name: Localization

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours - https://crontab.guru/#0_*/6_*_*_*
  push:
    paths:
      - 'l10n'
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: crowdin action
        uses: crowdin/github-action@1.5.1
        with:
          # Upload sources to Crowdin
          upload_sources: true
          # Download translations from Crowdin
          download_translations: true
          # Upload new translations from the repo to Crowdin
          upload_translations: true

          # To download translations to the specified version branch
          localization_branch_name: l10n_crowdin_translations

          # Create pull request after pushing to branch
          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
